[versions]
# plugins
intelliJPlatform = "2.10.5"
errorpronePlugin = "4.3.0"
grammarKit = "2023.3.0.1"
asciidoctorConvert = "4.0.5"
junit = "6.0.2"

[libraries]
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit"}
junitVintageEngine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit"}
junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit"}

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
errorpronePlugin = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
grammarKit = { id = "org.jetbrains.grammarkit", version.ref = "grammarKit" }
asciidoctorConvert =  { id = 'org.asciidoctor.jvm.convert', version.ref = "asciidoctorConvert" }
