[versions]
# plugins
intelliJPlatform = "2.2.1"
errorpronePlugin = "4.1.0"
grammarKit = "2022.3.2.2"
asciidoctorConvert = "4.0.3"

[libraries]

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
errorpronePlugin = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
grammarKit = { id = "org.jetbrains.grammarkit", version.ref = "grammarKit" }
asciidoctorConvert =  { id = 'org.asciidoctor.jvm.convert', version.ref = "asciidoctorConvert" }
